version: 0.2

phases:
  pre_build:
    commands:
      - REPOSITORY_URI=3498xxxxxx.dkr.ecr.ap- danortheast-2.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...         
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
      