version: 0.2

phases:
  pre_build:
    commands:
      - cd project2-restaurant
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: project2-restaurant/build